### ISSUE TITLE
ReviewActivity : Overall Layout

### ISSUE THREAD

**Issue by SeojinSeojin** [BE-SOPT-28th-OliveYoung-Redesign/OliveYoung_Android#2]

**Comment by SeojinSeojin** [comment]
![2021-05-18 17 09 21](https://user-images.githubusercontent.com/48249505/118615757-0183f980-b7fc-11eb-9354-286a84b17fa5.gif)

리사이클러뷰는 코드로만 존재하고 아직 어답터 붙이지 않았습니다

**Comment by SeojinSeojin** [comment]
* 위에는 칩으로 하고, 밑에는 드로어블로 만들어서 크기 및 패딩이 다른데
* 어느걸로 통일하는게 좋을지 조언 부탁해요~

**Comment by jooyae** [comment]
- 밑에 Drawable 크기로 통일하는게 저는 좋을 것 같은데, 서진님이 선택하시면 될 것 같아요 😊
